import Providers from "@/lib/Providers";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ToastContainer } from "react-toastify";

import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Timeless Jewellery",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <html lang="en">
        <body
          className={`${inter.className}  scrollbar-hide max-w-7xl mx-auto`}
        >
          <div className="min-h-screen">{children}</div>
          <ToastContainer
            position="top-right"
            autoClose={3000}
            theme="colored"
          />
        </body>
      </html>
    </Providers>
  );
}
